const path = require('path');

const BACKEND_ROOT = path.join(__dirname, '..');
const WORKSPACE_ROOT = path.join(BACKEND_ROOT, '..');
const UPLOAD_DIR = path.join(BACKEND_ROOT, 'tmp', 'uploads');

const MAX_ASSIGNMENT_SHUFFLE = 50;
const ROSTER_PREFIX = '[ROSTER]';
const DEFAULT_PROFESSOR_PASSWORD = 'prof123';
const MAX_UPLOAD_SIZE_BYTES = 50 * 1024 * 1024; // 50 MB
const DEFAULT_RUBRIC_ITEM_KEY = 'item_1';
const DEFAULT_RUBRIC_ITEM_TEXT = 'Calidad general';
const DEFAULT_RUBRIC_ITEM_WEIGHT = 100;
const RUBRIC_SCORE_MIN = 0;
const RUBRIC_SCORE_MAX = 10;

module.exports = {
  BACKEND_ROOT,
  WORKSPACE_ROOT,
  UPLOAD_DIR,
  MAX_ASSIGNMENT_SHUFFLE,
  ROSTER_PREFIX,
  DEFAULT_PROFESSOR_PASSWORD,
  MAX_UPLOAD_SIZE_BYTES,
  DEFAULT_RUBRIC_ITEM_KEY,
  DEFAULT_RUBRIC_ITEM_TEXT,
  DEFAULT_RUBRIC_ITEM_WEIGHT,
  RUBRIC_SCORE_MIN,
  RUBRIC_SCORE_MAX
};
